server:
  port: 8090
spring:
  application:
    name: ms-claim-c
  profiles:
    active: local
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ms-claim-c
#        tags: 乐约理赔C端
#        prefer-ip-address: true
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#      config:
#        enabled: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

#  mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
